language: node_js
sudo: false
node_js:
- stable
cache:
  directories:
    - node_modules
before_script:
- npm install -g bower
- bower install
env:
  global:
  - SELENIUM_HOST=hub.browserstack.com
  - SELENIUM_PORT=80
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
  - secure: Tzetr/lCBSbCOC6E/keZiHg7zJhTTEmeUU8HzsMxfLu1jt5lFsmelSitOkyIvnMHN8KofmxvACYUBropipLv4Sgntxwo9kj/PCqYwUvieblA83+K1KwsyKaepLDBtfkSLj4+MnP6bLdf+tHwrAC/JVhrexsQSQZl7Mhq88u5/OEoP2I3XEI6IwcJ0OobcrxN03pL+y3PjKTwTl4PG87dHesE32zfMx/TQepx+8tmIrWOFNtM4NVSfD019dFzgVPUoDuO/1jLnbqtwScX0JbiHw5AR7rhAMjLlKpxgYvxa81x661EF+ndMUpRTdxMXziosuM+S5gtcQcRikyQKAd0UWjIcGydrBw6YSxP9u2CVnE0ykj8/jflapQEJp0YoYvh6IEvDHklpRAEENfkSvztOeOVhDi00ANDDQMAjvENmxJ/9t4O3NDwQ2GnOQtyMuo772rF8yxbsap35Gd+ubdHXzm6iPk5u3IsGofPcTPj/gfqughWUk2ZPKo8ZrInUcI2an5ab8eghuOM3q07VGT58xLtjl6oQRf6fl1hFdM4ieLuJtbOYue2kvX19Wiav2h+zFcxzhv8k5cMGfmYguxX0hwalXBxbnLXRtT8L2Pxv7clgcs4kTFhtLNjMvcDCL2kBXG2eIKia4YPn4KwemAU8WQvY3HM4hL1qe4N4KvYIL0=
  - secure: S3Q0pynZGgfC+NrrnTh4k2e7f+z7e/+teGHb+1tkxxlrFOip7PHil5faJguftNokrBB04FQYruOX7UitM6x/Ic9H/Bl40Le/WQf2uH6ONpFZsr1udEsH7vWlFP8I7gaWZ54oMg3DBE6QMM1s67XXg6eH9e8Jd9lKgysq335Hs9gvQ7zYG0MAPYuSOcbE/40Hv576/Z2b0ZDQVmwCJ1BbgcrbCFHYmIn09XWuLWA9Oi4vBuqv6plLm4Y68+lcjWgdrtZNs1Bh8xLKNI715VUYHdbZrtpWkDUGFIv2RFNaPIqZjLthLYJtnrIwptmX9orD6BtX3ZIpLFaWx5Emxc7sMRrWoDll5jv9YxYrSLVr9Qn83oxqUK4A95Zx3/sjAegnB6i1MQMhoi9hUee5Jjbb3HsWHFC4y227332XcmSoAeWpxDPtI99aBHM4WSElOkqxxuNOZwKR4BlfpvBEPSG72LDQ866geXRJLv7XBpWO6GFOUvJl7vjhzG4Q3jjFxd/7NM5naR+XQh+a+p7mJXlcOXy1MlKRQyv+bs83XIci1WbkQNeVtt/iXMHnU37Qg3mComD5EyeB5J0q0rlts9tHjQSGI2Vblezilgxe4QqhPaA9ErS8weGnufyjyIzfhHXNDkTjRcSNqBvRkHkNubeOiyt8vjkHgEOEjC/QUFqrJUE=
script:
  - npm run test:deploy
deploy:
  provider: npm
  email: andrewjdodson@gmail.com
  on:
    tags: true
    repo: MrSwitch/tricks
    all_branches: true
  api_key:
    secure: PYWJQVQVYokJ/fCTPaD3iFgjYFXjH7D9DSlEk0BSeqpZkxKvQT489slXfwmjFjXa1I+TtGXoo4smtjgy+BgYMT6vTBOJeYtsC/JZbuEqrRnYqQwb/zRSIKlZzihrTO8sySmNQHsdxC2xvYRRvQ1a/u8aYVxhtIPLAOZx3YUjy96HCfl2MwH3/A4z1zJGB920KMrzy9H+447PSwuagSKHHKIv4YMYDal/yDaUVX1/Vx9Xho0zlfqhFrkerOwYCswQkevvOOZ/qLvUYKhL0e3m+yxMYe3QFk48/ttF+ZZqzbCnzIGA4M20i5optgyeictD1dmjoDXLAe34oiJaKUuNuTXB+MN2wpuvmAZu7o27i9zr0G6qzSsvz6O0c192s4+zbnJ+KqCANetNiKxbRMChh/c3D6AKjeSrOZapd0YQWvpWY9QRj8j3MbZ8SVXBNjotg0EaZd1cs8lKuVWSbgVB4YtD58t1x+Rdf3I6PtixwWooSC4qGUDV0JSryIVaPvh7Emlim9eG841U8Yd0ht+5r3AImJ5hgpE71Zx+bcXW+NegQNYzT9Jj950bUIpz38fBPin8Kc77I9KBfY4Z+tT6FFu130tYBoLCEoc9+MGNEshW61hd+8ebK32dmENzxv98JuZaoOFMB6181Hb6YlNrPlwjL6aOHfk5SwcfovLUzew=
